services:
  - type: web
    name: segurese-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        generateValue: true
      - key: EMAIL_PASS
        generateValue: true
